//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaweUploadFileChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpload
    {
        public int UploadId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Category { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string ExpenseDescription { get; set; }
        public Nullable<decimal> PreTaxAmount { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    }
}
